# Generated by Django 5.2.10 on 2026-03-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auditlog_basket_order_commission_orderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True, help_text='List any allergens, e.g. Contains eggs'),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='Date of harvest or production', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_status',
            field=models.CharField(choices=[('in_season', 'In Season'), ('out_of_season', 'Out of Season'), ('all_year', 'Available All Year'), ('limited', 'Limited Availability')], default='all_year', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('item', 'Item'), ('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml'), ('bunch', 'Bunch'), ('pack', 'Pack'), ('dozen', 'Dozen')], default='item', max_length=20),
        ),
    ]
