# Generated by Django 5.2.10 on 2026-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_allergen_info_product_harvest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic_certification_status',
            field=models.CharField(choices=[('certified_organic', 'Certified Organic'), ('not_certified', 'Not Certified')], default='not_certified', max_length=25),
        ),
    ]
