# Generated by Django 5.2.10 on 2026-03-25 16:33

import marketplace.services.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[marketplace.services.file_validators.validate_image_file_extension, marketplace.services.file_validators.validate_image_file_size, marketplace.services.file_validators.validate_image_content_type]),
        ),
    ]
