# Generated by Django 5.2.10 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_product_low_stock_threshold_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
