# Generated by Django 5.2.10 on 2026-04-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_stockalert_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(help_text='Brief review title', max_length=200)),
                ('review_text', models.TextField(help_text='Detailed review')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide customer name in public display')),
                ('producer_response', models.TextField(blank=True, help_text="Producer's response to the review")),
                ('producer_response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order where the product was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='marketplace.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='marketplace_product_3e1506_idx')],
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
