# Generated by Django 5.2.10 on 2026-04-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_productreview'),
        ('orders', '0004_order_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(help_text='Order where the product was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='orders.order'),
        ),
    ]
