# Generated by Django 5.2.10 on 2026-05-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_productreview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seasonal_end_date',
            field=models.DateField(blank=True, help_text='End of seasonal availability (e.g., August 31 for summer produce)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_start_date',
            field=models.DateField(blank=True, help_text='Start of seasonal availability (e.g., June 1 for summer produce)', null=True),
        ),
    ]
