# Generated by Django 5.2.10 on 2026-03-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('accounts', '0002_customuser_delivery_address_customuser_phone_and_more'),
    ]

    operations = [
    ]
